# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-02-18 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CDRRecording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_direction', models.CharField(choices=[('i', 'INCOMMING'), ('o', 'OUTGOING')], max_length=1)),
                ('calling_number', models.CharField(max_length=20)),
                ('called_number', models.CharField(max_length=20)),
                ('call_time', models.DateTimeField()),
                ('duration', models.DecimalField(decimal_places=3, max_digits=15)),
                ('remote_ip', models.GenericIPAddressField()),
                ('recording', models.FileField(upload_to=b'')),
            ],
            options={
                'db_table': 'cdr_recording',
            },
        ),
        migrations.CreateModel(
            name='PhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, unique=True, verbose_name='Phone Number *')),
            ],
            options={
                'db_table': 'phone_numbers',
            },
        ),
        migrations.CreateModel(
            name='SystemLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_by', models.CharField(max_length=128)),
                ('action_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('action_desc', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'system_logs',
            },
        ),
        migrations.CreateModel(
            name='TaggedPhoneNumbers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_upto', models.DateTimeField()),
                ('enable', models.BooleanField(default=True)),
                ('last_modified_on', models.DateTimeField(blank=True, null=True)),
                ('i_phone', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='li.PhoneNumbers', verbose_name='Phone Number *')),
            ],
            options={
                'db_table': 'tagged_phone_numbers',
            },
        ),
        migrations.AddField(
            model_name='cdrrecording',
            name='i_tagged_phone_numbers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='li.TaggedPhoneNumbers'),
        ),
    ]
